# COCO 2017 dataset http://cocodataset.org - first 128 training images
# Train command: python train.py --data coco128.yaml
# Default dataset location is next to /yolov5:
#   /parent_folder
#     /coco128
#     /yolov5

# 使用锚点引用
dataset_dir: &dataset_dir "/home/tml/datasets/enpo_dataset/endo_polyp_13182"

# download command/URL (optional)
# download: ~
# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: 
  - *dataset_dir/images/train
val:
  - *dataset_dir/images/val
test:
  - *dataset_dir/images/test

# number of classes
nc: 1

#names: ['lymph node','blood flow', 'hilum', 'calcification']  # 删除了4个'space-occupying lesion'和 1个'colliquative necrosis'
#names: ['lymph_node', 'peripheral_blood_flow', 'eccentric_blood_flow', 'central_blood_flow', 'unknown_blood_flow',
#    'hilum', 'liquefactive_necrosis', 'space_occupying_lesion', 'calcification']
# names: ['lymph_node']
names: ['polyp']  #